# Generated by Django 4.2.1 on 2023-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
